title: Người Ấy Là Ai Database
email: nguyenhongphat28121998@gmail.com
description: >-
  Người Ấy Là Ai Database. Thông tin tổng hợp về các nhân vật trong Người Ấy Là Ai. Wiki, Database, Info,...
baseurl: ""
url: "https://nguoiaylaai.github.io/"
github_username:  nguyenhongphat0
menus:
  - Trang chủ
  - Những chàng trai
  - Thông tin

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
